name: ${project.name}
main: space.arim.omega.plugin.OmegaPlugin
version: ${project.version}
author: A248
description: ${project.description}
depend: [ArimAPI, ServerStarter, Vault]
load: STARTUP

commands:
  pay:
    aliases: [/transact]
    usage: /pay
    description: Pay another player
  bal:
    aliases: [balance]
    usage: /bal
    description: See player balance
  baltop:
    aliases: [richest]
    usage: /baltop
    description: See top balances
  altcheck:
    aliases: [alts]
    usage: /altcheck <player>
    description: Altcheck a player